@startchen

entity Fabricante {
    cnpj <<key>>
    nome <<NOT NULL>>
    endereco
    contato
}

entity Produto {
    id <<key>>
    nome <<NOT NULL>>
    codigoDeBarras <<UNIQUE, NOT NULL>>
    preco <<NOT NULL>>
    descricao
    quantidadeEmEstoque 
}

entity Estoque {
    id <<key>>
    nome <<NOT NULL>>
    localizacao
    quantidade 
}

entity Funcionario {
    cpf <<key>>
    nome <<NOT NULL>>
    telefone
    email <<UNIQUE>>
    papel
    password 
}

entity Representante {
    cpf <<key>>
    nome <<NOT NULL>>
    telefone
    email
}


entity Movimentacao {
    id <<key>>
    dataEHora
    quantidade
    produto <<FK>>
    funcionario <<FK>>
    estoque <<FK>>
    tipoDeTransacao
}

Fabricante =(N,N)= Produto
Representante =(N,N)= Fabricante 
Estoque =(N,N)= Produto 
Produto =(N,N)= Fabricante 
Funcionario =(N,N)= Estoque
Produto =(N,N)= Movimentacao
Estoque =(N,N)= Movimentacao
Funcionario =(N,N)= Movimentacao
@endchen